### ISSUE TITLE
Quick Question for a Hackthon: Feel Free to close

### ISSUE THREAD

**Issue by Qodestackr** [aragon/osx#465]
I know this does not align with how issues should be opened.Am participating on ETHSafari hackathon, in Kenya and my blockchain of choice is Aragon. I know it will make it seamless to build. But how do I get a test net? Do I use external tools like Rinkeby or Aragon has one?

**Comment by Michael-A-Heuer** [comment]
Aragon is a smart contract protocol running on certain EVM compatible blockchain networks (currently Ethereum, Base,and Polygon) that all have their respective test networks.
I suggest you to learn about how Ethereum infrastructure and tooling works here: https://ethereum.org/en/developers/
