### ISSUE TITLE
Bug: Unable to create a DAO on Polygon

### ISSUE THREAD

**Issue by Oskii** [aragon/osx#514]
**Describe the bug**
The final step of DAO creation throws the following error:

```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="latestRelease()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at E.makeError (index.js:224:23)
    at E.throwError (index.js:233:20)
    at z.decodeFunctionResult (interface.js:345:23)
    at $.<anonymous> (index.js:293:48)
    at Generator.next (<anonymous>)
    at o (index.js:5:58)
```

*NETWORK UNSUPPORTED

**To Reproduce (please complete the following information)**

1. Go to https://app.aragon.org/#/create
2. Switch your network to Polygon
3. Attempt to deploy a DAO on Polygon with the following parameters

Network: Mainnet
Blockchain: Polygon
Logo: <Add a PNG>
Name: Oscar's Aragon DAO
Summary: I'm just doing this as a test

**Current behavior**

The console throws the following error and a dao is not created

```
*NETWORK UNSUPPORTED
api-stg.vocdoni.net/v2/accounts/0xEe0861faBEdc0BD4E41fe9fE97E6Cd1c7e4B717a:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
network.tsx:62 *NETWORK UNSUPPORTED
api-stg.vocdoni.net/v2/accounts/0xEe0861faBEdc0BD4E41fe9fE97E6Cd1c7e4B717a:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
4createDao.tsx:516 Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="latestRelease()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at E.makeError (index.js:224:23)
    at E.throwError (index.js:233:20)
    at z.decodeFunctionResult (interface.js:345:23)
    at $.<anonymous> (index.js:293:48)
    at Generator.next (<anonymous>)
    at o (index.js:5:58)
```

**Expected behavior**

A DAO creation transaction should be created via my Metamask wallet. 

**System (please complete the following information):**

- OS: [e.g. Windows 11 Pro]
- Software version [Google Chrome Version 120.0.6099.71 (Official Build) (64-bit)]
- Metamask [11.7.0]

**Comment by Oskii** [comment]
After a few attempts I was eventually able to do it. Potentially there is an RPC issue?

https://polygonscan.com/tx/0x04920054d95b7ccf0f51f82d0abca48351dd6d1e0b2e391f8b0b75a6803bb373

**Comment by Michael-A-Heuer** [comment]
Hey, sorry to hear that you had these troubles @Oskii . I redirected you request to the https://github.com/aragon/app team.

**Comment by Michael-A-Heuer** [comment]
FYI: Right now, we experience issues in other parts of the App frontend too.

**Comment by Michael-A-Heuer** [comment]
Moved to https://github.com/aragon/app/issues/1179
