### ISSUE TITLE
Deploy Aragon OSx on Sepolia

### ISSUE THREAD

**Issue by aahna-ashina** [aragon/osx#525]

**Comment by Michael-A-Heuer** [comment]
Hey @aahna-ashina, Aragon OSx is already deployed on Sepolia

https://github.com/aragon/osx/blob/54ae5922fdff5c4c976f0112fef88c3327c72a97/active_contracts.json#L119-L156

However, the Aragon App frontend doesn't show it yet.
If you want it to be on the App frontend, you could open an issue here: https://github.com/aragon/app. 
We are already in the process of adding it there.

**Comment by aahna-ashina** [comment]
@Michael-A-Heuer Done:  https://github.com/aragon/app/issues/1205
